site_name: SHAARP

nav:
    - Getting started: install.md
    - Methods: methods.md
    - Input Parameters: input.md
    - Output Results: output.md
    - Examples: examples.md
    - Frequently Asked Questions (FAQ): FAQ.md
    - Table of Symbols: table.md

theme: readthedocs
