site_name: SHAARP

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  
nav:
    - Home: index.md
    - Getting started: install.md
    - Methods: methods.md
    - Input Parameters: input.md
    - Output Results: output.md
    - Examples: examples.md
    - Frequently Asked Questions (FAQ): FAQ.md
    - Table of Symbols: table.md

theme: readthedocs
